version: '3.7'
services:
  currency-exchange:
    image: in28min/currency-exchange:0.0.1
    ports:
    - "8080:8000"
    restart: always
    networks:
    - currency-compose-network

  currency-conversion:
    image: in28min/currency-conversion:0.0.1
    ports:
    - "8081:8100"
    restart: always
    environment: 
      CURRENCY_EXCHANGE_SERVICE_HOST: http://currency-exchange
    depends_on:
    - currency-exchange
    networks:
    - currency-compose-network